# Generated by Django 3.0.4 on 2020-04-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='bookinstance',
            name='language',
        ),
        migrations.RemoveField(
            model_name='bookinstance',
            name='status',
        ),
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(blank=True, choices=[('o', 'On Lend'), ('a', 'Available')], default='a', help_text='book availability', max_length=1),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(help_text='Select a genre for this book', null=True, to='books.Genre'),
        ),
    ]
