# Generated by Django 3.0.4 on 2020-04-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20200413_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='status',
        ),
        migrations.AddField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('w', 'With borrower'), ('r', 'Requested'), ('j', 'Rejected')], default='r', help_text='book availability', max_length=1),
        ),
    ]
