# Generated by Django 3.0.4 on 2020-03-30 14:50

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('catalog', '0002_auto_20200330_2013'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Owner',
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
            ],
            options={
                'ordering': ['last_name', 'first_name'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
